#!/bin/sh

SSHD_PORT=2222

speak_ssh(){
  echo "
  User connected via SSH.
  Connection from $(echo $SSH_CONNECTION | awk '{ print $1 " to phone at " $3 }')
  " | termux-tts-speak
}

notice_ssh(){
  termux-notification \
      --priority high \
      -t 'Login via SSH' \
      -c "$(date)" \
      --id ssh_login \
      --icon warning \
      --button1 "Terminate SSH" \
      --button1-action 'killall sshd' \
      --button2 "Restart SSH" \
      --button2-action "sshd -p $SSHD_PORT" \
      --button3 "Dismiss" \
      --button3-action 'termux-notification-remove ssh_login'
}

notice_ssh
speak_ssh
